workspace:
  base: /go
  path: src/github.com/metalmatze/transmission-exporter

pipeline:
  build:
    image: golang:alpine
    commands:
      - apk add -U git make
      - make fmt
      - make vet
      - make lint
      - make build

  docker:
    image: plugins/docker
    repo: metalmatze/transmission-exporter
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
    when:
      event: [ push ]
      branch: [ master ]

  docker:
    image: plugins/docker
    repo: metalmatze/transmission-exporter
    secrets: [ docker_username, docker_password ]
    tag: [ 0.2 ]
    when:
      event: tag
