# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
- GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- main: ./cmd/transmission-exporter/
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
dockers:
  - binaries:
    - transmission-exporter
    image_templates:
    - "metalmatze/transmission-exporter:latest"
    - "metalmatze/transmission-exporter:{{ .Tag }}"
    - "metalmatze/transmission-exporter:{{ .Major }}.{{ .Minor }}"
