{
 "title": "Transmission",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Session Downloaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_downloaded_bytes{type=\"current\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Time Downloaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_downloaded_bytes{type=\"cumulative\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Time Uploaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{type=\"cumulative\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session Uploaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{type=\"current\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Torrents",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(transmission_torrent_status != -1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downloading From",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(transmission_torrent_peers_sending_to_us)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Download Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_download_speed_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Upload Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_upload_speed_bytes"
    }
   ]
  },
  {
   "title": "Seeding To",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(transmission_torrent_peers_getting_from_us)"
    }
   ]
  },
  {
   "title": "Global Ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{type=\"cumulative\"} / transmission_session_stats_downloaded_bytes{type=\"cumulative\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload / Download Speeds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "transmission_session_stats_download_speed_bytes",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "transmission_session_stats_upload_speed_bytes",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Upload Speed by Torrent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(5, transmission_torrent_upload_bytes)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Torrents",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "transmission_torrent_added * 1000",
     "legendFormat": "Added"
    },
    { "expr": "transmission_torrent_done", "legendFormat": "Done" },
    {
     "expr": "transmission_torrent_downloaded_ever_bytes",
     "legendFormat": "Bytes Downloaded"
    },
    {
     "expr": "transmission_torrent_peers_getting_from_us",
     "legendFormat": "Leechers"
    },
    {
     "expr": "transmission_torrent_peers_sending_to_us",
     "legendFormat": "Seeders"
    },
    { "expr": "transmission_torrent_ratio", "legendFormat": "Ratio" },
    {
     "expr": "transmission_torrent_uploaded_ever_bytes",
     "legendFormat": "Bytes Uploaded"
    },
    { "expr": "transmission_torrent_status", "legendFormat": "Status" },
    {
     "expr": "transmission_torrent_upload_bytes",
     "legendFormat": "Upload Speed"
    },
    {
     "expr": "transmission_torrent_download_bytes",
     "legendFormat": "Download Speed"
    }
   ]
  },
  {
   "title": "Incomplete Torrents",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transmission_torrent_done < 1", "legendFormat": "{{name}}" }
   ]
  }
 ]
}