{
 "title": "Transmission",
 "description": "Transmission statistics prometheus dashboard ",
 "tags": [
  "prometheus",
  "transmission"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Torrent",
    "query": {
     "query": "label_values(transmission_torrent_ratio,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of torrents",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(transmission_torrent_done)"
    }
   ]
  },
  {
   "title": "Current upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{type=\"current\"}"
    }
   ]
  },
  {
   "title": "1 day upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(transmission_session_stats_uploaded_bytes{type=\"cumulative\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "7 days upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(transmission_session_stats_uploaded_bytes{type=\"cumulative\"}[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{type=\"cumulative\"}"
    }
   ]
  },
  {
   "title": "Current upload speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (transmission_torrent_upload_bytes{name=~\"$Torrent\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{type=\"current\"}/transmission_session_stats_downloaded_bytes{type=\"current\"}"
    }
   ]
  },
  {
   "title": "Cumulative ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{type=\"cumulative\"}/transmission_session_stats_downloaded_bytes{type=\"cumulative\"}"
    }
   ]
  },
  {
   "title": "Current download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_downloaded_bytes{type=\"current\"}"
    }
   ]
  },
  {
   "title": "1 day download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(transmission_session_stats_downloaded_bytes{type=\"cumulative\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "7 days download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(transmission_session_stats_downloaded_bytes{type=\"cumulative\"}[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_downloaded_bytes{type=\"cumulative\"}"
    }
   ]
  },
  {
   "title": "Current download speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (transmission_torrent_download_bytes{name=~\"$Torrent\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload rate / minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "transmission_torrent_upload_bytes{name=~\"$Torrent\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Torrents stats",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avg_over_time (transmission_torrent_upload_bytes{name=~\"$Torrent\"}[30d])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "transmission_torrent_ratio{name=~\"$Torrent\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "transmission_torrent_files_total{name=~\"$Torrent\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time (transmission_torrent_seeders{name=~\"$Torrent\"}[30d])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "avg_over_time (transmission_torrent_leechers{name=~\"$Torrent\"}[30d])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "transmission_torrent_added{name=~\"$Torrent\"} * 1000",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "transmission_torrent_downloads_total{name=~\"$Torrent\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "transmission_torrent_upload_bytes{name=~\"$Torrent\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "avg_over_time (transmission_torrent_upload_bytes{name=~\"$Torrent\"}[1d])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "transmission_torrent_peers_connected{name=~\"$Torrent\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "transmission_torrent_peers_getting_from_us{name=~\"$Torrent\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "transmission_torrent_total_size{name=~\"$Torrent\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "transmission_torrent_uploaded_ever{name=~\"$Torrent\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}